CREATE DATABASE oops CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `foo`
(
    `id`          BIGINT   NOT NULL AUTO_INCREMENT COMMENT 'Foo ID',
    `description` VARCHAR(255) NULL COMMENT '설명',
    `created_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Foo 엔티티';

CREATE USER 'oops'@'localhost' IDENTIFIED BY 'oops1234';
GRANT ALL PRIVILEGES ON oops.* TO 'oops'@'localhost';
FLUSH PRIVILEGES;